// Code generated by MockGen. DO NOT EDIT.
// Source: post.go
//
// Generated by this command:
//
//	mockgen -source=post.go -destination=./mock_post.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	model "blog-platform/model"
	reflect "reflect"

	v4 "github.com/labstack/echo/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockPostServiceInterface is a mock of PostServiceInterface interface.
type MockPostServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPostServiceInterfaceMockRecorder
}

// MockPostServiceInterfaceMockRecorder is the mock recorder for MockPostServiceInterface.
type MockPostServiceInterfaceMockRecorder struct {
	mock *MockPostServiceInterface
}

// NewMockPostServiceInterface creates a new mock instance.
func NewMockPostServiceInterface(ctrl *gomock.Controller) *MockPostServiceInterface {
	mock := &MockPostServiceInterface{ctrl: ctrl}
	mock.recorder = &MockPostServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostServiceInterface) EXPECT() *MockPostServiceInterfaceMockRecorder {
	return m.recorder
}

// CreatePost mocks base method.
func (m *MockPostServiceInterface) CreatePost(ctx v4.Context, post *model.Post) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", ctx, post)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockPostServiceInterfaceMockRecorder) CreatePost(ctx, post any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockPostServiceInterface)(nil).CreatePost), ctx, post)
}

// RetrieveAllPosts mocks base method.
func (m *MockPostServiceInterface) RetrieveAllPosts(ctx v4.Context) ([]model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveAllPosts", ctx)
	ret0, _ := ret[0].([]model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetrieveAllPosts indicates an expected call of RetrieveAllPosts.
func (mr *MockPostServiceInterfaceMockRecorder) RetrieveAllPosts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveAllPosts", reflect.TypeOf((*MockPostServiceInterface)(nil).RetrieveAllPosts), ctx)
}

// RetrievePostByID mocks base method.
func (m *MockPostServiceInterface) RetrievePostByID(ctx v4.Context, id string) (model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrievePostByID", ctx, id)
	ret0, _ := ret[0].(model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetrievePostByID indicates an expected call of RetrievePostByID.
func (mr *MockPostServiceInterfaceMockRecorder) RetrievePostByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrievePostByID", reflect.TypeOf((*MockPostServiceInterface)(nil).RetrievePostByID), ctx, id)
}
